name: build-pyside6

on:
  workflow_call:
    inputs: 
      createrelease:
        type: boolean
        default: false
        required: false 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: write

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            qthost: linux
            qtarch: gcc_64
            version: 6.10.0
            pythonversion: 3.10.5
            arch: x64
            binding: PySide6

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.qtarch }}
          host: ${{ matrix.qthost }}
          target: desktop
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pythonversion }}
          architecture: ${{ matrix.arch }}
      
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
        with:
          arch: ${{ matrix.arch }}
      
      - run: python scripts/dobuild.py ${{ matrix.pythonversion }} ${{ matrix.qtarch }} ${{ matrix.version }} ${{ matrix.arch }} ${{ matrix.binding }}
      
      - uses: actions/attest-build-provenance@v2.2.0
        with:
          subject-path: scripts/objects
      
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.qthost }}_${{ matrix.binding }}_${{ matrix.arch }}
          path: scripts/objects
